#!/usr/bin/env python
"""Build every number and table the paper uses from analysis outputs.

    python scripts/paper_assets.py --out <paper dir> \
        --run main=results_main/results --run sd35=kaggle_out/sd35m_merged/results [--run klein=...]

Writes <out>/numbers.tex  (\\EV{<run>:<key>} for every value in each numbers.json)
       <out>/tables/*.tex (tables generated from the CSVs; never edit by hand)
A run that is missing simply yields \\PENDING in the tables that need it.
"""
from __future__ import annotations

import argparse
import json
import os

import numpy as np
import pandas as pd

PEND = r"\PENDING"


def f3(v, d=3):
    try:
        v = float(v)
    except (TypeError, ValueError):
        return PEND
    return PEND if np.isnan(v) else f"{v:.{d}f}"


def fp(p):
    """p-value for a table cell."""
    try:
        p = float(p)
    except (TypeError, ValueError):
        return PEND
    if np.isnan(p):
        return "--"
    if p < 1e-10:
        return r"$<\!10^{-10}$"
    if p < 1e-3:
        e = int(np.floor(np.log10(p)))
        return rf"${p / 10 ** e:.1f}{{\times}}10^{{{e}}}$"
    return f"{p:.3f}"


def esc(s: str) -> str:
    return str(s).replace("_", r"\_").replace("%", r"\%")


def tex_value(v, key: str = "") -> str:
    if key.endswith("_p") and isinstance(v, (int, float)) and not isinstance(v, bool):
        if v < 1e-10:
            return r"\ensuremath{<10^{-10}}"
        if v < 1e-3:
            e = int(np.floor(np.log10(v)))
            return rf"\ensuremath{{{v / 10 ** e:.1f}\times10^{{{e}}}}}"
        return f"{v:.3f}"
    if v is None:
        return "n/a"
    if isinstance(v, bool):
        return str(v)
    if isinstance(v, int):
        return f"{v:,}".replace(",", "{,}")
    if isinstance(v, float):
        if np.isnan(v):
            return "n/a"
        if v != 0 and abs(v) < 1e-3:
            e = int(np.floor(np.log10(abs(v))))
            return rf"\ensuremath{{{v / 10 ** e:.1f}\times10^{{{e}}}}}"
        return f"{v:.3f}"
    return esc(v)


def write_numbers(runs: dict, out: str):
    lines = ["% generated by scripts/paper_assets.py -- do not edit",
             r"\providecommand{\EV}[1]{\ifcsname ev@#1\endcsname\csname ev@#1\endcsname\else\PENDING\fi}"]
    for name, d in runs.items():
        p = os.path.join(d, "numbers.json")
        if not os.path.exists(p):
            continue
        for k, v in sorted(json.load(open(p)).items()):
            lines.append(rf"\expandafter\def\csname ev@{name}:{k}\endcsname{{{tex_value(v, k)}}}")
    for name, d in runs.items():  # derived values that only exist as CSVs
        a = os.path.join(d, "alpha_sweep.csv")
        if os.path.exists(a):
            t = pd.read_csv(a)
            for k, v in (("alpha_dgini_min", t.mean_abs_dgini.min()), ("alpha_dgini_max", t.mean_abs_dgini.max())):
                lines.append(rf"\expandafter\def\csname ev@{name}:{k}\endcsname{{{tex_value(float(v))}}}")
    open(os.path.join(out, "numbers.tex"), "w").write("\n".join(lines) + "\n")
    return len(lines) - 2


def read(runs, name, csv):
    p = os.path.join(runs.get(name, ""), csv)
    return pd.read_csv(p) if name in runs and os.path.exists(p) else None


def table(path, cols, header, rows, caption, label, star=False, size=None):
    size = size or (r"\footnotesize" if star else r"\scriptsize")
    env = "table*" if star else "table"
    body = "\n".join(" & ".join(r) + r" \\" for r in rows) if rows else \
        r"\multicolumn{" + str(len(cols)) + r"}{c}{\PENDING} \\"
    tex = (rf"\begin{{{env}}}[t]" "\n\\centering\n" rf"\caption{{{caption}}}\label{{{label}}}" "\n"
           f"{size}\n" + ("" if star else "\\setlength{\\tabcolsep}{3pt}\n") + rf"\begin{{tabular}}{{{cols}}}" "\n\\toprule\n" f"{header} \\\\\n\\midrule\n"
           f"{body}\n\\bottomrule\n\\end{{tabular}}\n\\end{{{env}}}\n")
    open(path, "w").write(tex)


MODEL = {"sd14": "SD~1.4", "sd15": "SD~1.5", "biggan": "BigGAN", "sd35-medium": "SD~3.5-M",
         "flux2-klein-base": "FLUX.2-klein", "qwen-image": "Qwen-Image", "sd": "SD (cons.)",
         "coco": "COCO (real)", "magicbrush": "MagicBrush"}
DS = {"multiguide_coco_v2": "v2", "multiguide_coco_v3": "v3", "multiguide_consistency": "stab.",
      "Erland__coco_captions_small": "real", "kaggle_sd35m": "ext.", "coco": "ext."}


def t_corpus(runs, tdir):
    rows = []
    for name in runs:
        d = read(runs, name, "corpus_summary.csv")
        if d is None:
            continue
        if name != "main":
            d = d[d.corpus != "real"]  # real photos are counted once, in the main run
        for (c, ds, m), g in d.groupby(["corpus", "dataset", "model"]):
            modes = ", ".join(esc(x) for x in g["mode"])
            rows.append([esc(c), DS.get(ds, esc(ds)), MODEL.get(m, esc(m)), modes, f"{int(g.n.sum()):,}".replace(",", "{,}")])
    total = sum(int(r[-1].replace("{,}", "")) for r in rows)
    rows.append([r"\textbf{Total}", "", "", "", rf"\textbf{{{total:,}}}".replace(",", "{,}")])
    table(f"{tdir}/corpus.tex", "lllp{4.2cm}r", "Corpus & Split & Generator & Conditions & Images",
          rows, "EvidGeo composition. Every generated image is paired with the real COCO photograph of its caption.",
          "tab:corpus", star=True)


def t_guidance(runs, tdir):
    d = read(runs, "main", "guidance_tests.csv")
    rows = []
    if d is not None:
        for (ds, m, a, b), g in d.groupby(["dataset", "model", "a", "b"], sort=False):
            cells = [DS.get(ds, ds), MODEL.get(m, m), f"{a}$-${b}", str(int(g.n.max()))]
            for s in ("pec", "rollout", "ss"):
                r = g[g.signal == s]
                cells += [f3(r.dz.iloc[0], 2), fp(r.p_holm.iloc[0])] if len(r) else ["--", "--"]
            rows.append(cells)
    table(f"{tdir}/guidance.tex", "llcr" + "rr" * 3,
          r"Split & Model & Contrast & $n$ & \multicolumn{2}{c}{Grad-PEC} & \multicolumn{2}{c}{Rollout} & "
          r"\multicolumn{2}{c}{SpatialShap} \\ & & & & $d_z$ & $p$ & $d_z$ & $p$ & $d_z$ & $p$",
          rows, r"Guidance contrasts in evidence concentration (Gini), paired by prompt. $d_z$: paired "
                r"effect size; $p$: Holm-corrected over all reported tests.", "tab:guidance", star=True)


def t_sweep(runs, tdir):
    rows = []
    for name in ("sd35", "klein", "qwen"):
        d = read(runs, name, "guidance_sweep.csv")
        if d is None:
            continue
        for _, r in d[d.measure.isin(["pec_gini", "ss_gini", "rollout_gini", "clipscore",
                                      "pec_seed_sem_var", "pec_seed_jsd"])].iterrows():
            means = {k[8:]: r[k] for k in d.columns if k.startswith("mean_cfg") and not pd.isna(r[k])}
            seq = r" $\to$ ".join(f3(v) for _, v in sorted(means.items(), key=lambda kv: float(kv[0])))
            rows.append([MODEL.get(r.model, esc(r.model)), esc(r.measure), ", ".join(sorted(means, key=float)),
                         seq, f3(r.slope_logcfg, 4), fp(r.p)])
    table(f"{tdir}/sweep.tex", "llllrr",
          r"Model & Measure & Guidance $s$ & Mean per $s$ & Slope ($\log s$) & $p$", rows,
          r"Guidance sweeps on current models. Slopes from $y\sim\log s+\text{prompt}$ fixed effects, "
          r"prompt-clustered errors.", "tab:sweep", star=True)


def t_stability(runs, tdir):
    d = read(runs, "main", "stability_tests.csv")
    rows = []
    if d is not None:
        for _, r in d.iterrows():
            rows.append([esc(r.measure), f"{r.a}$-${r.b}", str(int(r.n)), f3(r.mean_a, 4), f3(r.mean_b, 4),
                         f3(r.dz, 2), fp(r.p_holm)])
    table(f"{tdir}/stability.tex", "llrrrrr", r"Measure & Contrast & $n$ & Mean $a$ & Mean $b$ & $d_z$ & $p$",
          rows, "Cross-seed stability on the consistency corpus (150 prompts, 3 seeds per mode), paired by prompt.",
          "tab:stability")


def t_faith(runs, tdir):
    d = read(runs, "main", "faithfulness.csv")
    rows = []
    if d is not None:
        for _, r in d.iterrows():
            rows.append([esc(r.a), esc(r.b), r.kind, str(int(r.n)), f3(r.mean_a, 4), f3(r.mean_b, 4), fp(r.p_wilcoxon)])
    table(f"{tdir}/faithfulness.tex", "lllrrrr", r"Map $a$ & Map $b$ & Curve & $n$ & AUC $a$ & AUC $b$ & $p$", rows,
          "Deletion (lower is more faithful) and insertion (higher is more faithful) AUC of CLIP similarity, "
          "paired on the same images.", "tab:faith")


def t_detection(runs, tdir):
    d = read(runs, "main", "detection.csv")
    rows = []
    if d is not None:
        for _, r in d.iterrows():
            rows.append([esc(r.task.replace("_RESOLUTION_CONFOUNDED", r"$^\dagger$")), esc(r.features),
                         f"{int(r.n):,}".replace(",", "{,}"), f3(r.chance), f"{f3(r.acc)}$\\pm${f3(r.acc_sd)}",
                         f3(r.macro_f1)])
    table(f"{tdir}/detection.tex", "llrrrr", r"Task & Features & $n$ & Chance & Accuracy & Macro-F1", rows,
          r"Linear probes, 5-fold cross-validation grouped by caption. $^\dagger$Confounded by resolution "
          r"(BigGAN 256\,px vs.\ SD 512\,px).", "tab:detection")


def t_realgen(runs, tdir):
    d = read(runs, "main", "real_vs_generated.csv")
    rows = []
    if d is not None:
        for _, r in d[d.signal == "pec"].iterrows():
            rows.append([DS.get(r.dataset, r.dataset), MODEL.get(r.model, r.model), esc(r["mode"]), str(int(r.n)),
                         f3(r.mean_a), f3(r.mean_b), f3(r.dz, 2), fp(r.p_holm)])
    table(f"{tdir}/realgen.tex", "lllrrrrr", r"Split & Model & Mode & $n$ & Gini gen. & Gini real & $d_z$ & $p$", rows,
          "Generated vs.\\ paired real photograph (Grad-PEC Gini), paired by caption.", "tab:realgen")


def t_masks(runs, tdir):
    rows = []
    for name in runs:
        d = read(runs, name, "mask_evidence.csv")
        if d is None:
            continue
        for _, r in d.iterrows():
            rows.append([MODEL.get(r.model, esc(r.model)), esc(r["mode"]), str(int(r.n)), f3(r.area)] +
                        [f3(r.get(f"{s}_ratio"), 2) for s in ("pec", "rollout", "loo", "ss")])
    table(f"{tdir}/masks.tex", "llrr" + "r" * 4,
          r"Model & Task & $n$ & Area & Grad-PEC & Rollout & LOO & SpatialShap", rows,
          "Evidence inside the inpainted or edited region relative to its area (1 = no preference).",
          "tab:masks")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    ap.add_argument("--run", action="append", default=[], help="name=results_dir")
    a = ap.parse_args()
    runs = dict(r.split("=", 1) for r in a.run)
    os.makedirs(os.path.join(a.out, "tables"), exist_ok=True)
    n = write_numbers(runs, a.out)
    td = os.path.join(a.out, "tables")
    for fn in (t_corpus, t_guidance, t_sweep, t_stability, t_faith, t_detection, t_realgen, t_masks):
        fn(runs, td)
    print(f"{n} numbers, {len(os.listdir(td))} tables -> {a.out}")


if __name__ == "__main__":
    main()
